import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import matplotlib
matplotlib.use("Agg")
from datetime import date, timedelta
import matplotlib.pyplot as plt

from src_trinomial.tree import Tree
from src.option_trade import OptionTrade
from src.market import Market
from src_trinomial.trinomial_model import TrinomialModel
from src.black_scholes import BlackScholes

PLOTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plots")
os.makedirs(PLOTS_DIR, exist_ok=True)

import time
import math

# --- Paramètres globaux ---
S0 = 100.0
K  = 102.0
r  = 0.05
sigma = 0.3
div_a = 0
ex_div_date = date(2026, 8, 21)

pricing_date = date(2025, 9, 1)
mat_date = date(2026, 9, 1)

# --- Conversion en années pour Black–Scholes ---
T = (mat_date - pricing_date).days / 365.0

# --- Prix Black-Scholes (benchmark) ---
_bs_market = Market(underlying=S0, vol=sigma, rate=r, div_a=div_a, ex_div_date=ex_div_date)
_bs_option = OptionTrade(mat=mat_date, call_put="CALL", ex="EUROPEAN", k=K)
bs_price = BlackScholes(_bs_market, _bs_option, pricing_date).price()
print(f"Black-Scholes Call price: {bs_price:.6f}")

# --- Paramètres du test de convergence ---
max_steps = 1500
tree_prices = []

def convex_steps(max_steps: int, power: float = 1.6, small_cutoff: int = 30) -> list[int]:
    """
    Return a sorted list of step counts with convex spacing:
    - include all integers 1..small_cutoff for fine resolution at small N
    - then add values generated by i**power up to max_steps (convex growth)
    """
    steps = set(range(1, min(small_cutoff, max_steps) + 1))
    # choose n so that i**power will reach ~max_steps
    n = math.ceil(max_steps ** (1.0 / power))
    for i in range(1, n + 1):
        v = int(round(i ** power))
        if v < 1:
            v = 1
        if v > max_steps:
            v = max_steps
        steps.add(v)
    steps.add(max_steps)
    return sorted(steps)

# generate steps (tweak power to change convexity: >1 convex, =1 linear)
steps = convex_steps(max_steps=max_steps, power=1.6, small_cutoff=30)
print(f"Will compute prices for {len(steps)} points from {steps[0]} to {steps[-1]}")

# --- Boucle de convergence ---
for N in steps:
    market = Market(
        underlying=S0,
        vol=sigma,
        rate=r,
        div_a=div_a,
        ex_div_date=ex_div_date
    )

    option_trade = OptionTrade(
        mat=mat_date,
        call_put="CALL",
        ex="EUROPEAN",
        k=K
    )

    tree = Tree(nb_step=N, market=market, option=option_trade, pricing_date=pricing_date)
    tree.build_tree()

    model = TrinomialModel(pricing_date=pricing_date, tree=tree)
    price_tree = model.price(option_trade)
    tree_prices.append(price_tree)

    #feedback
    #print(f"N={N:3d} -> Tree price = {price_tree:.6f}, BS Price = {bs_price:.6f}, error = {abs(price_tree - bs_price):.6e}")

# --- Plot convergence ---
plt.figure(figsize=(11,6))
plt.plot(steps, tree_prices, marker='o', markersize=4, label="Trinomial Tree")
plt.axhline(bs_price, color="red", linestyle="--", label="Black-Scholes")
plt.xlabel("Number of steps N")
plt.ylabel("Option Price")
plt.title("Convergence of Trinomial Tree to Black-Scholes")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'trinomial_convergence_price.png'), dpi=150)
plt.close()
print(f"✓ Saved trinomial_convergence_price.png")

# --- Plot absolute error ---
errors = [abs(p - bs_price) for p in tree_prices]

plt.figure(figsize=(11,5))
plt.plot(steps, errors, marker='o', markersize=4)
plt.yscale('log')   # utile pour voir la décroissance
plt.xlabel("Number of steps N")
plt.ylabel("Absolute error (log scale)")
plt.title("Absolute error between Trinomial Tree and Black-Scholes")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'trinomial_convergence_error.png'), dpi=150)
plt.close()
print(f"✓ Saved trinomial_convergence_error.png")

# --- Plot scaled error (error_bis) ---
error_bis = [
    (p - bs_price) * n if (p is not None and not (isinstance(p, float) and math.isnan(p))) else math.nan
    for p, n in zip(tree_prices, steps)
]
plt.figure(figsize=(11,5))
plt.plot(steps, error_bis, marker='o', markersize=4, label="Scaled error (N * (tree - BS))")
plt.xlabel("Number of steps N")
plt.ylabel("Scaled error: N * (tree - BS)")
plt.title("Scaled error (N * (Tree price - Black-Scholes))")
plt.axhline(0.0, color="black", linewidth=0.6, linestyle="--")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.savefig(os.path.join(PLOTS_DIR, 'trinomial_convergence_scaled.png'), dpi=150)
plt.close()
print(f"✓ Saved trinomial_convergence_scaled.png")

#version sans dividende 
"""from datetime import date, timedelta
import matplotlib.pyplot as plt
from PriceurBS import Call            # Black-Scholes pricer (T en années)
from classModelTriniomial import Market, OptionTrade, Tree, TrinomialModel

# --- Paramètres globaux ---
S0 = 100.0
K  = 150.0
r  = 0.05
T  = 1.0            # maturité en années pour Black-Scholes
sigma = 0.5

# Dates pour le tree : pricing_date et mat_date
pricing_date = date.today()
mat_date = pricing_date + timedelta(days=int(T * 365))

# --- Prix Black-Scholes (benchmark) ---
bs_call = Call(S=S0, K=K, r=r, T=T, sigma=sigma,
               div_a=2.5, ex_div_date=pricing_date + timedelta(days=100),
               pricing_date=pricing_date)

bs_price = bs_call.price()
print(f"Black-Scholes Call price: {bs_price:.6f}")

# --- Paramètres du test de convergence ---
max_steps = 200        # augmente si tu veux (attention au temps d'exécution)
tree_prices = []
steps = list(range(1, max_steps + 1))

# Pas de dividende pour ce test ; si besoin passer div_a>0 et ex_div_date
for N in steps:
    # delta_t interne au Tree est calculé à partir des dates, on passe N
    market = Market(underlying=S0, vol=sigma, rate=r, div_a=0.0, ex_div_date=None)
    option_trade = OptionTrade(mat=mat_date, call_put="CALL", ex="EUROPEAN", k=K)

    tree = Tree(nb_step=N, market=market, option=option_trade, pricing_date=pricing_date)
    tree.build_tree()

    model = TrinomialModel(pricing_date=pricing_date, tree=tree)
    price_tree = model.price(option_trade)
    tree_prices.append(price_tree)

    # feedback
    if N % 10 == 0 or N == 1:
        print(f"N={N:3d} -> Tree price = {price_tree:.6f}, error = {abs(price_tree - bs_price):.6e}")

# --- Plot convergence ---
plt.figure(figsize=(11,6))
plt.plot(steps, tree_prices, marker='o', markersize=4, label="Trinomial Tree")
plt.axhline(bs_price, color="red", linestyle="--", label="Black-Scholes")
plt.xlabel("Number of steps N")
plt.ylabel("Option Price")
plt.title("Convergence of Trinomial Tree to Black-Scholes Price (no dividends)")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

# --- Plot absolute error ---
errors = [abs(p - bs_price) for p in tree_prices]
plt.figure(figsize=(11,5))
plt.plot(steps, errors, marker='o', markersize=4)
plt.yscale('log')   # utile pour voir la décroissance
plt.xlabel("Number of steps N")
plt.ylabel("Absolute error (log scale)")
plt.title("Absolute error between Trinomial Tree and Black-Scholes")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()"""
